services:
  ghost:
    image: ghost:6-alpine
    restart: unless-stopped
    environment:
      url: https://amalfi.day/blog
      NODE_ENV: production
      server__host: 0.0.0.0
      server__port: 40001
      database__client: mysql
      database__connection__host: shared-mysql
      database__connection__user: ghost
      database__connection__password: EuXORAZQaK-JBQ2VNH5Y1otG
      database__connection__database: ghost
      security__staffDeviceVerification: false
      mail__transport: SMTP
      mail__options__host: smtp.eu.mailgun.org
      mail__options__port: 587
      mail__options__secure: "false"
      mail__options__auth__user: postmaster@amalfi.day
      mail__options__auth__pass: ${MAIL_SMTP_PASS}
      mail__from: Amalfi.Day <noreply@amalfi.day>
      mailgun__apiKey: ${MAILGUN_API_KEY}
      mailgun__domain: amalfi.day
      mailgun__baseUrl: https://api.eu.mailgun.net/v3
    ports:
      - "127.0.0.1:40001:40001"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    volumes:
      - ghost_content:/var/lib/ghost/content
    networks:
      - web-proxy
      - shared_mysql

volumes:
  ghost_content:

networks:
  web-proxy:
    external: true
  shared_mysql:
    external: true
